global:
  region: us-east-1
  env: dev
  tenant: dev01
  vectorEfsID: "fs-029ce9b520f183983"
  vectorIamRole: "arn:aws:iam::010526270844:role/us-east-1-vector"
  vectorS3Backup: arn:aws:s3:::dev1-vector-sink-backup
  kafkaClusterName: kafka

vectorManager:
  role: &role vector-manager

  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi

  autoscaling:
    enabled: false

  image:
    repository: omrikas/vectorwip
    version: 0.0.1

  persistentVolume:
    name: "vector-efs"
    csiDriver: efs.csi.aws.com
    volumeHandle: "{{ .Values.global.vectorEfsID }}" 
    reclaimPolicy: Retain
    volumes:
      - name: vector
        mounts:
          - mountPath: /vector/

  serviceAccount:
    create: true
    name: vector
    iamRole: "{{ .Values.global.vectorIamRole }}" 

  nodeSelector:
    karpenter.sh/nodepool: node-mixed

  podAnnotations:
    iam.amazonaws.com/role: vector

  networkPolicy:
    name: *role
    egress: |
      - to:
        - namespaceSelector:
            matchLabels:
              name: "kube-system"
        ports:
          - protocol: TCP
            port: 53 # DNS Resolver

  environmentVariables:
    VECTOR_CONFIG: /vector/source1.yaml