{{- define "common.configMap.tpl" -}}
{{- $top := first . }}
{{- $cm := index . 1 }}
{{- $path := $cm.mountPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "common.metadata" (list $top false $cm) | nindent 2 }}
  {{- with $cm.annotations }}
  annotations:
        {{- toYaml . | trim | nindent 4 }}
  {{- end }}
data:
  {{- range $path, $config := $cm.data }}
  {{ $path }}: |
  {{- tpl $config $top | nindent 4 }}
  {{- end -}}
{{- end }}

{{- define "common.configMap" -}}
{{- include "common.utils.merge" (append . "common.configMap.tpl") }}
{{- end }}
