{{- define "common.kafkanodepool.tpl" -}}
{{- $top := first . }}
{{- $kafkanodepool := index . 1 }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  {{- include "common.metadata" (list $top $kafkanodepool) | nindent 2 }}
    strimzi.io/cluster: {{ $kafkanodepool.name }}
spec:
  replicas: {{ $kafkanodepool.replicas | default 2 }}
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: {{ default "10Gi" ($kafkanodepool.storageSize | quote) }}
    class: gp3
    deleteClaim: false
    kraftMetadata: shared
{{- end }}

{{- define "common.kafkanodepool" -}}
  {{- include "common.utils.merge" (append . "common.kafkanodepool.tpl") }}
{{- end }}
