{{- define "common.pdb.tpl" -}}
{{- $top := first . }}
{{- $pdb := index . 1 }}
{{- if $pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  {{- include "common.metadata" (list $top false $pdb) | nindent 2 }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (list $top $pdb)| nindent 6 }}
  {{- if not (or (empty $pdb.minAvailable) (empty $pdb.maxUnavailable)) }}
    {{- fail "minAvailable and maxUnavailable can not be set together" }}
  {{- end }}
  {{- with $pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with $pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}

{{- define "common.pdb" -}}
{{- $top := first . }}
{{- $pdb := index . 1 }}
{{- $deployment := index . 2 }}
{{- $autoscaling := index . 3 }}
{{- if or (and $autoscaling.enabled (gt ($autoscaling.maxReplicas | int) 1)) (and (not $autoscaling.enabled) (gt ($deployment.replicaCount | int) 1)) }}
  {{- include "common.utils.merge" (append . "common.pdb.tpl") }}
{{- end }}
{{- end }}
