{{- define "common.role.tpl" -}}
{{- $top := first . }}
{{- $role := index . 1 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "common.metadata" (list $top $role ) | nindent 2 }}
rules:
  {{ tpl $role.rules $top | nindent 2 }}
{{- end }}

{{- define "common.role" -}}
{{- include "common.utils.merge" (append . "common.role.tpl") }}
{{- end }}
