{{- define "common.roleBinding.tpl" -}}
{{- $top := first . }}
{{- $roleBinding := index . 1 }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "common.metadata" (list $top false $roleBinding ) | nindent 2 }}
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ tpl $roleBinding.roleRef.name $top}}
subjects:
  {{- toYaml $roleBinding.subjects | nindent 2 }}
{{- end }}

{{- define "common.roleBinding" -}}
{{- include "common.utils.merge" (append . "common.roleBinding.tpl") }}
{{- end }}
