{{- define "common.secret.tpl" -}}
{{- $top := first . }}
{{- $secret := index . 1 }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "common.metadata"  (list $top false) | nindent 2 }}
  {{- with $secret.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $secret }}
    {{ .name }}: {{ .base64data  }}
  {{- end }}
{{- end }}

{{- define "common.secret" -}}
{{- include "common.utils.merge" (append . "common.secret.tpl") }}
{{- end }}
