{{- define "common.serviceAccount.tpl" -}}
{{- $top := first . }}
{{- $serviceAccount := index . 1 }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if or $serviceAccount.annotations $serviceAccount.iamRole }}
  annotations:
    {{- with $serviceAccount.iamRole }}
    eks.amazonaws.com/role-arn: {{ tpl . $top }}
    eks.amazonaws.com/sts-regional-endpoints: "true"
    {{- end }}
    {{- with $serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- include "common.metadata" (list $top $serviceAccount) | nindent 2 }}
{{- end }}

{{- define "common.serviceAccount" -}}
{{- $top := first . }}
{{- $serviceAccount := index . 1 }}
  {{- if $serviceAccount.create }}
  {{- include "common.utils.merge" (append . "common.serviceAccount.tpl") }}
  {{- end }}
{{- end }}
