{{- define "common.service.tpl" -}}
{{- $top := first . }}
{{- $service := index . 1 }}
apiVersion: v1
kind: Service
metadata:
  {{- include "common.metadata" (list $top false $service) | nindent 2 }}
  {{- with $service.annotations }}
  annotations:
    {{- include "common.utils.tplYaml" (list . $top) | nindent 4 }}
  {{- end }}
spec:
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  type: {{ $service.type }}
  ports:
  {{- with $service.ports }}
      {{- range . }}
  - port: {{ .port }}
    targetPort: {{ .targetPort | default .port }}
    protocol: {{ .protocol | default "TCP" }}
        {{- if .name }}
    name: {{ .name }}
        {{- end }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "common.selectorLabels" (list $top $service)| nindent 4 }}
{{- end }}
{{- define "common.service" -}}
{{- include "common.utils.merge" (append . "common.service.tpl") }}
{{- end }}
