global:
  region: us-east-1
  env: dev
  tenant: dev01
  vectorEfsID: "fs-029ce9b520f183983"
  vectorIamRole: "arn:aws:iam::010526270844:role/us-east-1-vector"
  vectorS3Backup: arn:aws:s3:::dev1-vector-sink-backup

tenant:
  kafka:
    name: kafka
    storageSize: 10