apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2


  amiSelectorTerms:
  - name: "amazon-eks-arm64-node*"
    owner: amazon

  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 10Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: us-east-1-eks-nodes-role
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: us-east-1-eks
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: us-east-1-eks
  userData: |
    #!/bin/bash
    set -o xtrace
    sysctl -w net.core.wmem_max=26214400
    sysctl -w net.core.rmem_max=26214400
    /etc/eks/bootstrap.sh us-east-1-eks --kubelet-extra-args '--register-with-taints="karpenter.sh/unregistered:NoExecute" --image-gc-low-threshold=60 --image-gc-high-threshold=70 --eviction-hard="imagefs.available<5%,memory.available<10Mi,nodefs.available<2%,nodefs.inodesFree<1%" --eviction-soft="imagefs.available<15%,memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%" --eviction-soft-grace-period="imagefs.available=60s,memory.available=60s,nodefs.available=60s,nodefs.inodesFree=60s" --eviction-max-pod-grace-period=90'