apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: node-mixed
spec:
  disruption:
    budgets:
    - nodes: 30%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 4
    memory: 4Gi
  template:
    metadata:
      labels:
        karpenter-nodepool: node-mixed
    spec:
      expireAfter: 119h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-family
        operator: NotIn
        values:
        - m3
        - c5ad
        - u7i
        - u7in
        - u7i-12tb
        - u7in-16tb
        - u7in-32tb
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-cpu
        operator: Lt
        values:
        - "8"
      - key: karpenter.k8s.aws/instance-memory
        operator: Lt
        values:
        - "8192"
      terminationGracePeriod: 1h