global:
  region: us-east-1
  env: dev
  tenant: dev01
  vectorEfsID: "fs-029ce9b520f183983"
  vectorIamRole: "arn:aws:iam::010526270844:role/us-east-1-vector"
  vectorS3Backup: arn:aws:s3:::dev1-vector-sink-backup
  kafkaClusterName: kafka

sourceAlphaVector:
  role: &role alpha-vector

  environmentVariables:
    VECTOR_CONFIG: /vector/frontend.yaml

  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 2048Mi

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    cooldownPeriod: 30
    triggers:
      cpuUtilizationPercentage: 60
      memoryUtilizationPercentage: 60

  image:
    repository: timberio/vector
    version: 0.47.0-debian

  persistentVolume:
    name: "vector-efs"
    csiDriver: efs.csi.aws.com
    volumeHandle: "{{ .Values.global.vectorEfsID }}" 
    reclaimPolicy: Retain
    volumes:
      - name: vector
        mounts:
          - mountPath: /vector/

  serviceAccount:
    create: true
    name: vector
    iamRole: "{{ .Values.global.vectorIamRole }}" 

  nodeSelector:
    karpenter.sh/nodepool: node-mixed

  podAnnotations:
    iam.amazonaws.com/role: vector

  networkPolicy:
    name: *role
    egress: |
      - to:
        - namespaceSelector:
            matchLabels:
              name: "kube-system"
        ports:
          - protocol: TCP
            port: 53 # DNS Resolver

  # TODO:- implement container port listeners list
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations: |-
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "1514"
    ports:
    - port: 12
    - port: 13
    - port: 14
    - port: 15